var topics = [
    "http://dbpedia.org/resource/Charity_(virtue)",
    "http://dbpedia.org/resource/Four_causes",
    "http://dbpedia.org/resource/Occasionalism",
    "http://dbpedia.org/resource/Physical_body",
    "http://dbpedia.org/resource/Summum_bonum",
    "http://dbpedia.org/resource/Desire",
    "http://dbpedia.org/resource/God",
    "http://dbpedia.org/resource/Love",
    "http://dbpedia.org/resource/Love_of_God",
    "http://dbpedia.org/resource/Pain_(philosophy)",
    "http://dbpedia.org/resource/Passions_(philosophy)",
    "http://dbpedia.org/resource/Philosophy_of_mind",
    "http://dbpedia.org/resource/Pleasure#Philosophies_of_pleasure",
    "http://dbpedia.org/resource/Sensation_(psychology)",
    "http://dbpedia.org/resource/Soul",
    "http://dbpedia.org/resource/Will_(philosophy)",
    "http://dbpedia.org/resource/Will_of_God"
    ]
